
-- CREATING A TABLE WITH CONSTRAINTS

CREATE TABLE sales(
		purchase_number INT AUTO_INCREMENT,
        date_of_purchase DATE,
        customer_id INT,
        item_code VARCHAR(10),
PRIMARY KEY (purchase_number)
-- FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE
-- ON DELETE CASCADE : IF ANY RECORD IN THE PARENT TABLE DELETED, THEN THE VALUES REFERING IN THE CHILD TABLE WILL ALSO BE DELETED
-- IF A PARTICULAR CUSTOMER IS NOT AVAILABLE ANY MORE IN PARENT TABLE THEN IT'S SENSIBLE TO DELETE RECORDS IN SALES (CHILD) TABLE TOO
);

-- YOU CAN ADD FOREIGN KEY WHEN CREATING THE TABLE, ELSE YOU CAN ALTER IT LATER WITH THE FOLLOWING QUERY
ALTER TABLE sales ADD FOREIGN KEY (customer_id) REFERENCES customer(customer_id);







-- Assignment from 365Careers BI
